### ISSUE TITLE
http cannot have access to username 

### ISSUE THREAD

**Issue by ruipang1122** [risdenk/webhdfs-dotnet#15]
I got this exception:
HttpRequestException: Response status code does not indicate success: 100 (Continue).
then I checked the http request:
 {"RemoteException":{"exception":"AccessControlException","javaClassName":"org.apache.hadoop.security.AccessControlException","message":"Permission denied: user=dr.who, access=WRITE, inode=\"/user\":t-rupang:supergroup:drwxr-xr-x\r\n\tat org

I think it is because we use networkcredential for username and password fields.

**Comment by ruipang1122** [comment]
Please give me some hints~~~
The http request sent to hdfs does not contain username. It is 'Dr who' by default.
I would be very appreciate if you can help me out :）

**Comment by risdenk** [comment]
Do you have Kerberos enabled on your Hadoop cluster?

**Comment by risdenk** [comment]
Closing as stale.
