### ISSUE TITLE
How to authenticate against Kerberos enabled cluster?

### ISSUE THREAD

**Issue by sambit19** [risdenk/webhdfs-dotnet#17]
1. I am trying getting a token successfully
` public string authenticate(string url)
        {
            string op_literal = "?op=";
            string operation = "GETDELEGATIONTOKEN";
            string domain = ReadDomain();
            string user = ReadUsername();
            SecureString pass = ReadPassword();
            HttpWebRequest request;
            HttpWebResponse response;
            //First get the delegation token from the URL
            request = (HttpWebRequest)WebRequest.Create(url + op_literal + operation);

            CredentialCache cc = new CredentialCache();
            cc.Add(new Uri(url + op_literal + operation), "Negotiate", (
                        (domain == null || domain == "") ?
                        new System.Net.NetworkCredential(user, pass) :
                        new System.Net.NetworkCredential(user, pass, domain)));

            request.Credentials = cc;
            request.CookieContainer = new CookieContainer();

            response = (HttpWebResponse)request.GetResponse();
            // Display the status.  
            Console.WriteLine(((HttpWebResponse)response).StatusDescription);
            // Get the stream containing content returned by the server.  
            Stream dataStream = response.GetResponseStream();
            // Open the stream using a StreamReader for easy access.  
            StreamReader reader = new StreamReader(dataStream);
            // Read the content.  
            string responseFromServer = reader.ReadToEnd();
            // Display the content.  
            Console.WriteLine(responseFromServer);
            // Clean up the streams and the response.  
            reader.Close();
            response.Close();
            return responseFromServer;
        }`

2. As second step I am passing this token in the URL after ?delegation=

Is this the right way? I noticed Kerberos support is not available in the master

**Comment by risdenk** [comment]
If this is working then shouldn't have a problem.

**Comment by sambit19** [comment]
Somehow in the second step passing the delegation token in the URL gives me a bad request error. Passing the delegation token is done in GET request, whereas the Upload file happens through PUT.  I can not combine delegation and op=CREATE in one request for example.

**Comment by risdenk** [comment]
So back up a step here, I think you should be able to pass `NetworkCredential` directly to the constructor for WebHDFS client. Your example code doesn't use the library created here. 

Are you using the webhdfs-dotnet library to interact? Kerberos support should be there there just aren't any tests.

**Comment by sambit19** [comment]
I have cleaned up my code and just used the library webhdfs-dotnet. I still ended up getting the error
`"Should get a 307. Instead we got: Unauthorized Unauthorized"`

I have set this as well in the code(commented out Kerberos, to force it to be used)

 `          AuthenticationManager.Unregister("Basic");

            AuthenticationManager.Unregister("NTLM");

            AuthenticationManager.Unregister("Negotiate");

            AuthenticationManager.Unregister("Digest");

            //AuthenticationManager.Unregister("Kerberos");`

**Comment by sambit19** [comment]
Finally I could make it working with a Kerberized cluster. I had to set up the HttpClientHandler and it started working.

```
 NetworkCredential creds = new NetworkCredential(dt.ReadUsername(), dt.ReadPassword(),dt.ReadDomain());
            HttpClientHandler handler = new HttpClientHandler();
            handler.Credentials = creds;
            WebHDFSClient webhdfs = new WebHDFSClient(_baseAPI,
                creds,
                CustomHttpMessageHandler: handler);
            Stopwatch stopWatch = new Stopwatch();
            stopWatch.Start();
            Console.WriteLine("Do a directory listing");
            var result = webhdfs.GetFileStatus("/projects/test").Result;

           
            //var result = webhdfs.UploadFile(filename,hdfsFilename,overwrite: true).Result;
            Console.WriteLine("The response recieved: " + result);
```

**Comment by risdenk** [comment]
hmm interesting. Not sure how the custom handler is different than what the code is doing currently: https://github.com/risdenk/webhdfs-dotnet/blob/master/WebHDFS/WebHDFSClient.cs#L37

Thanks for the followup and glad it is working for you :)
